name: Build mod

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build mod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      matrix:
        java: ['11', '21' ]

    steps:
    - uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
        cache: gradle # Only cache stuff since test build action happen mostly
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Pnet.minecraftforge.gradle.disableUpdateChecker=true
    - name: Attest
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: 'build/libs'
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MekanismCEu
        path: build/libs
